spring:
  config:
    import: "optional:configserver:http://localhost:8888/"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  leve:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF